### ISSUE TITLE
Client cannot retrieve data model

### ISSUE THREAD

**Issue by mzillgith** [openmuc/openiec61850#1]
Hi, 
When I try to connect to a server with the console client (or GUI client) the association works but the retrieval of the data model doesn't work. Client stops with

`Service error: Error code=22`

Having a look with wireshark the client seems to send the exact GetNameList MMS PDU twice in the same message. I have seen that the server responds with a correct GetNameList response anyway.

![openiec61850-getmodel-problem](https://user-images.githubusercontent.com/25686324/29514339-7e61d52c-8668-11e7-8b6e-5d6ee760d981.png)

**Comment by mzillgith** [comment]
Seems that the client/server communication between openiec61850 client and server always duplicates the MMS PDU. The server also doesn't respond to other client's getNameList requests.

**Comment by sfeuerhahn** [comment]
yes, there was a bug encoding an and decoding the presentation layer introduced in v1.4.0. It should be fixed now.
Thanks!
