### ISSUE TITLE
Problem setting "Oper" structure (FC=CO)

### ISSUE THREAD

**Issue by danielePala** [openmuc/openiec61850#2]
I'm trying to write a "Oper" structure with functional constraint "CO" using the client GUI, but without success. The problem seems to be related to this instruction:

https://github.com/openmuc/openiec61850/blob/0fb4083d38752d4b9f6d95748d41aa6a01795d6b/src/main/java/org/openmuc/openiec61850/ServerAssociation.java#L1128

In fact, if I comment out this line the write operation seems to work. However, probably that instruction is there for a reason, so just commenting it out is not a very good solution.

**Comment by JosebaJ** [comment]
I'm having exactly the same issue.
As a workaround I've changed the icd file replacing the type of "ctlVal" from
/<BDA name="ctlVal" bType="Struct" type="AnalogueValue" //>
to /<BDA name="ctlVal" bType="FLOAT32" //>
In this way the mentioned line of code returns a BasicDataAttribute object and is not launching the exception.
This workaround is not compliant with the specifications of the standard so the issue should be solved in another way.

**Comment by sfeuerhahn** [comment]
I fixed this in 23a4715
Thanks for the bug report.
